### ISSUE TITLE
Latest binary archive places zcash-qt-wallet-v0.1.6 in bin directory

### ISSUE THREAD

**Issue by naconner** [adityapk00/zcash-qt-wallet#2]
Thanks for the wallet! Really cool. :+1:

I noticed that the latest binary archive placed the `zcash-qt-wallet-v0.1.6` directory within an initial `bin/` directory, though the preceding release didn't do similarly.

Thus, the readme to do this is off:
```
tar -xvf zcash-qt-wallet-v0.1.6.tar.gz
./zcash-qt-wallet-v0.1.6/zcash-qt-wallet
```

**Comment by adityapk00** [comment]
Thanks for the report. I've fixed it the build script so that it doesn't package it in the bin directory. I've also updated the release binary. 

https://github.com/adityapk00/zcash-qt-wallet/commit/07f5b4dc9fbac6a668571264187f51d4bd0f92c0
