### ISSUE TITLE
Copying address adds a line break

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/zcash-qt-wallet#3]
Tested with 0.1.6. If you copy an address on the “Balance” tab and right click “copy address” it adds a line break in there (which means it is invalid when you try and paste it in) i.e. pasting an address then looks like this
```
ztestsapling17nl3a6w42m6ydzqvrhgf93pvn78sedd
m4gh8qucwwjlkeylyhf3vcsg0x6vtzdqzalp4u5qe92r
```

**Comment by adityapk00** [comment]
Thanks for the report. Fixed in v0.1.7

Commit: d28ab79743e9fdda1f51769c8ba478bef465458f
