### ISSUE TITLE
The ordinal 315 could not be located in the dynamic link library

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/zcash-qt-wallet#6]
Seeing this on opening `zcash-qt-wallet.exe` on Windows 10 Home.

![Windows](https://user-images.githubusercontent.com/135382/47305731-44977500-d5df-11e8-8e1c-22d1b6b377bf.jpg)

Tested on v0.1.9

**Comment by adityapk00** [comment]
OK, this has me baffled :( 

While I figure out why this is happening, I've switched the Windows release to a full build which includes all dependencies. Hopefully that works. Can you download the v0.2.0 binaries and please give that a try?

**Comment by adityapk00** [comment]
What version of the OS are you using?

**Comment by garethtdavies** [comment]
Yes I am up and running with v0.2.0 👍
