### ISSUE TITLE
Default fee 0.0002 TAZ

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/zcash-qt-wallet#7]
On testnet the fee defaults to 0.0002. I'm guessing there is a dev fee in this which is fine but it shouldn't be hidden like this and should be a separate input as using the standard 0.0001 fee is strongly encouraged (as fees are visible on the blockchain). I think this layout confuses the matter.

![image](https://user-images.githubusercontent.com/135382/47306432-4b26ec00-d5e1-11e8-9360-6e62eb2b4668.png)

Tested on v0.1.9

**Comment by adityapk00** [comment]
Fixed. In v0.2.0 release

Commit: d6ce1f8b278066fa323be5b08ce8060a655c79b2 

![image](https://user-images.githubusercontent.com/31996805/47319920-cbab1400-d604-11e8-87ae-0c89773352d2.png)

**Comment by garethtdavies** [comment]
Awesome, that's much clearer. Just in case you haven't seen it the Zcash Foundation are looking for a cross-platform GUI wallet developer https://github.com/ZcashFoundation/ZcashFoundation/issues/73

**Comment by adityapk00** [comment]
Thanks for the tip. I reached out to the foundation on the issue.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
