### ISSUE TITLE
Created new recieving tAddr when new address is not created

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/zcash-qt-wallet#8]
If you click on the t-Addr radio button it displays in the footer "Created new recieving tAddr)" even if you don't create one.

Also minor but worth fixing with this is recieving is spelt incorrectly and also there is an inconsistent usage of t-Addr and tAddr. If space allows while these terms are used frequently address might be more appropriate?

![image](https://user-images.githubusercontent.com/135382/47325151-644a8f80-d617-11e8-966e-19eb48ef17fb.png)

**Comment by garethtdavies** [comment]
Actually, the word receiving is probably redundant anyway. Why not keep it consistent with other address types and the address isn't restricted to receiving so could be a point of confusion.

**Comment by adityapk00** [comment]
Actually, it automatically creates a new t-Addr when you click the radio button. This is special behaviour for t-Addrs, since we don't want users re-using t-Addrs. 

I've fixed the other 2 issues
commit: 0bec950e

**Comment by garethtdavies** [comment]
Ah thanks I didn't catch that. I was confused as the dropdown doesn't display addresses that haven't been used I guess but I can see all those have been generated in `getaddressbyaccount ""`

**Comment by adityapk00** [comment]
In v0.2.1
