### ISSUE TITLE
Amount doesn't accurately reflect fee

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/zcash-qt-wallet#9]
Sending a t-z transaction deducts 0.0002 in fees from my transparent address yet only 0.0001 is displayed in the amount. See this example where I sent 0.1 TAZ .

![image](https://user-images.githubusercontent.com/135382/47326435-9d85fe00-d61d-11e8-9fa1-9a013f1b80c3.png)

This is the txid on the explorer: https://explorer.testnet.z.cash/tx/7864b7110b5563c3bd89cc11cbeb89fe54be0d489d79287898de90cf60f34c51

**Comment by adityapk00** [comment]
This is unexpected behaviour from zcashd. It actually doesn't report the fees paid in the `listtransactions` RPC, so only the dev wallet fee is getting added. The tx fee of 0.0001 ZEC is missing. 

Maybe I should add it manually to the table? Or maybe even separate out the fees into a new column?

**Comment by adityapk00** [comment]
Oooh. The fee is in a separate field. Ok, that makes sense. I can fix this.

**Comment by adityapk00** [comment]
Fixed in commit 4d8debbbab71cff878efafa9284fb3aad5b5f185

**Comment by adityapk00** [comment]
In v0.2.1
